### PR TITLE
Packaging instructions/fixes

### PR DESCRIPTION
**Pull request by moio**
A few notes on how to rebuild the RPM package next time.

Also drops .spec/.changes - those will stay in OBS only.

### CODE REVIEW

**Review by admd — APPROVED** [review]

**Comment by juliogonzalez** [comment]
I don't recommend moving the spec and the changelog to OBS, but up to you.

In my experience that means wrong changelogs (missing entries, missing bscs, and more) much more frequently than when they stay with the code :-)

Why? Because the git history in 99% of the repositories is useless for changelog generation, but at the same time it's usually the only reference if you create the changelog during release/packaging time. And at that point people trust their memory, and that's not something to be trusted :-D

**Comment by moio** [comment]
@juliogonzalez I see your point - but currently we have no automation from git to OBS - it's done manually.

So at release time some developer has to change a text file with the changes - either in git (and then copy it to OBS) or directly in OBS. Do you see a very big difference in output quality? Or are you suggesting to tackle this with some git-to-OBS automation to begin with? (or maybe am I missing anything?)

**Comment by juliogonzalez** [comment]
> So at release time some developer has to change a text file with the changes - either in git (and then copy it to OBS) or directly in OBS. Do you see a very big difference in output quality? Or are you suggesting to tackle this with some git-to-OBS automation to begin with? (or maybe am I missing anything?)

No, not at release time. If you keep the changes file and the spec at the repository you can maintain the changelog file on the PRs. Even enforce tests. That way a PR changing code can also have changes on the changelog.

Then during release the developer just bumps the version on the spec and "closes" the changelog with a header.

Then there are the submissions to OBS, but that's another story. You will need submissions to OBS in all cases (regardless of where you have the SPEC and the changelogs), as I don't want direct submissions (commits) to the codestreams, but SRs.

For two reasons:
1. To review (spec and changelog)
2. To have control about "when" to merge a change.
So in either case, we'll need SRs to all affected codestreams.

**Comment by moio** [comment]
@juliogonzalez thanks, now I understand and agree with your point.

To move on, I am opening an issue and merging this PR.

https://github.com/uyuni-project/hub-xmlrpc-api/issues/63

**Pull request merged**
